# Advent of Code 2025 - Day 01 Carbon Solution

load("//bazel/carbon_rules:defs.bzl", "carbon_binary")

carbon_binary(
    name = "day01",
    srcs = [
        "day01.carbon",
        "io_utils.carbon",
    ],
)
